title: Documentaci贸n de API
logo: /assets/img/logo_blue.png
description: Documentaci贸n para la integraci贸n de terceros a la plataforma de Alfred por medio de API. Versi贸n 1.0.0
show_downloads: false
theme: jekyll-theme-minimal
